services:
  planka:
    image: ghcr.io/plankanban/planka:2.0.0-rc.4
    restart: on-failure
    volumes:
      - favicons:/app/public/favicons
      - user-avatars:/app/public/user-avatars
      - background-images:/app/public/background-images
      - attachments:/app/private/attachments
    # Optionally override this to your user/group
    # user: 1000:1000
    # tmpfs:
    #   - /app/.tmp:mode=770,uid=1000,gid=1000
    ports:
      - 3000:1337 
    env_file:
      - path: ./.env
        required: true # default
      - path: ./testing.env
        required: false
    
      # Using Gravatar directly exposes user IPs and hashed emails to a third party (GDPR risk).
      # Use a proxy you control for privacy, or leave commented out or empty to disable.
      # - GRAVATAR_BASE_URL=https://www.gravatar.com/avatar/
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planka"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  favicons:
  user-avatars:
  background-images:
  attachments:
  db-data: